###
# File: alacritty.toml
# Author: Leopold Johannes Meinel (leo@meinel.dev)
# -----
# Copyright (c) 2025 Leopold Johannes Meinel & contributors
# SPDX ID: Apache-2.0
# URL: https://www.apache.org/licenses/LICENSE-2.0
###

[general]
live_config_reload = true

[colors.primary]
background = '#282828'
foreground = '#ebdbb2'

[colors.normal]
black = '#282828'
red = '#cc241d'
green = '#98971a'
yellow = '#d79921'
blue = '#458588'
magenta = '#b16286'
cyan = '#689d6a'
white = '#a89984'

[colors.bright]
black = '#928374'
red = '#fb4934'
green = '#b8bb26'
yellow = '#fabd2f'
blue = '#83a598'
magenta = '#d3869b'
cyan = '#8ec07c'
white = '#ebdbb2'

[window]
padding = { x = 0, y = 0 }
decorations = "none"
decorations_theme_variant = "None"
opacity = 1.0
startup_mode = "Maximized"
title = "Alacritty"
dynamic_title = false
class = { instance = "Alacritty", general = "Alacritty" }

[scrolling]
history = 10000
multiplier = 3

[mouse]
hide_when_typing = true

[font]
size = 10
normal = { family = "HasklugNerdFontMono", style = "Regular" }
bold = { family = "HasklugNerdFontMono", style = "Bold" }
italic = { family = "HasklugNerdFontMono", style = "Italic" }
bold_italic = { family = "HasklugNerdFontMono", style = "Bold Italic" }

[env]
TERM = "alacritty"
